# Generated by Django 2.2.18 on 2024-08-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='picture_img',
            field=models.ImageField(blank=True, upload_to='article/%Y%m%d/'),
        ),
    ]
